import { Product, Category } from "../types/database";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Gourmet Foods",
    slug: "gourmet-foods",
    description:
      "Premium Italian ingredients and delicacies for the discerning palate",
    image:
      "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=800",
    parent_id: null,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Kitchen & Dining",
    slug: "kitchen-dining",
    description: "Artisan cookware and elegant tableware for your home",
    image:
      "https://images.pexels.com/photos/6996089/pexels-photo-6996089.jpeg?auto=compress&cs=tinysrgb&w=800",
    parent_id: null,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Home Decor",
    slug: "home-decor",
    description:
      "Beautiful Mediterranean-inspired pieces for your living space",
    image:
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
    parent_id: null,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Gift Collections",
    slug: "gift-collections",
    description: "Curated gifts for hosts, clients, and milestone moments",
    image:
      "https://images.pexels.com/photos/5874592/pexels-photo-5874592.jpeg?auto=compress&cs=tinysrgb&w=800",
    parent_id: null,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Tuscan Gold Extra Virgin Olive Oil",
    slug: "tuscan-gold-evoo",
    description:
      "This premium extra virgin olive oil is cold-pressed from hand-picked olives grown in the sun-drenched hills of Tuscany.",
    short_description:
      "Premium cold-pressed Tuscan olive oil with herbaceous notes",
    price: 45.99,
    original_price: 52.99,
    category_id: "1",
    brand: "Frantoio Toscano",
    sku: "EVOO-001",
    stock: 50,
    images: [
      "https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1022385/pexels-photo-1022385.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: {
      volume: "500ml",
      origin: "Tuscany, Italy",
      harvest: "2024",
    },
    rating: 4.8,
    review_count: 124,
    is_featured: true,
    is_new: false,
    tags: ["bestseller", "organic", "premium"],
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Artisan Bronze-Cut Spaghetti",
    slug: "artisan-bronze-cut-spaghetti",
    description:
      "Traditional spaghetti crafted using bronze dies and slow-dried for 48 hours.",
    short_description:
      "Traditional bronze-cut pasta with perfect sauce-holding texture",
    price: 12.99,
    original_price: null,
    category_id: "1",
    brand: "Pastificio Artigiano",
    sku: "PASTA-001",
    stock: 100,
    images: [
      "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { weight: "500g", cooking_time: "10-12 minutes" },
    rating: 4.7,
    review_count: 203,
    is_featured: true,
    is_new: false,
    tags: ["bestseller", "traditional", "bronze-cut"],
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "Parmigiano Reggiano 24 Months",
    slug: "parmigiano-reggiano-24",
    description:
      "The undisputed King of Cheeses, aged for 24 months in the traditional manner.",
    short_description: "The King of Cheeses, aged to perfection",
    price: 89.99,
    original_price: null,
    category_id: "1",
    brand: "Consorzio Parmigiano",
    sku: "CHEESE-001",
    stock: 25,
    images: [
      "https://images.pexels.com/photos/773253/pexels-photo-773253.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: {
      weight: "1kg wedge",
      origin: "Emilia-Romagna, Italy",
      aging: "24 months",
    },
    rating: 5.0,
    review_count: 234,
    is_featured: true,
    is_new: false,
    tags: ["dop", "aged", "bestseller"],
    created_at: new Date().toISOString(),
  },
  {
    id: "p4",
    name: "Hand-Painted Deruta Dinner Set",
    slug: "deruta-dinner-set",
    description:
      "A stunning 16-piece dinner set featuring the iconic Renaissance patterns of Deruta, Umbria.",
    short_description: "Artisan Italian ceramics for elegant dining",
    price: 289.99,
    original_price: 349.99,
    category_id: "2",
    brand: "Ceramiche Deruta",
    sku: "TABLE-001",
    stock: 10,
    images: [
      "https://images.pexels.com/photos/6996089/pexels-photo-6996089.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { pieces: "16", material: "Hand-painted majolica" },
    rating: 4.9,
    review_count: 45,
    is_featured: true,
    is_new: false,
    tags: ["handmade", "ceramics", "luxury"],
    created_at: new Date().toISOString(),
  },
  {
    id: "p5",
    name: "Sicilian Green Ceramic Serving Bowl",
    slug: "sicilian-green-ceramic-serving-bowl",
    description:
      "A glazed ceramic bowl inspired by Sicilian table settings, designed for antipasti, salads, and everyday serving.",
    short_description: "Glazed ceramic serving bowl with a refined green finish",
    price: 42.0,
    original_price: null,
    category_id: "2",
    brand: "Ceramiche Noto",
    sku: "TABLE-002",
    stock: 18,
    images: [
      "/images/mercato-hero-tableau.png",
    ],
    specifications: { diameter: "24cm", material: "Glazed stoneware" },
    rating: 4.8,
    review_count: 61,
    is_featured: true,
    is_new: true,
    tags: ["ceramics", "hosting", "new"],
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "p6",
    name: "Italian Olive Wood Cutting Board",
    slug: "italian-olive-wood-cutting-board",
    description:
      "A hand-finished olive wood board with expressive grain, sized for cheeses, breads, and aperitivo spreads.",
    short_description: "Hand-finished olive wood board for hosting",
    price: 38.0,
    original_price: 46.0,
    category_id: "2",
    brand: "Bottega del Legno",
    sku: "KITCHEN-003",
    stock: 34,
    images: [
      "/images/mercato-hero-tableau.png",
    ],
    specifications: { length: "38cm", care: "Hand wash only" },
    rating: 4.7,
    review_count: 87,
    is_featured: true,
    is_new: true,
    tags: ["olive-wood", "hosting", "giftable"],
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "p7",
    name: "Le Bonta del Casale Marinara Sauce",
    slug: "le-bonta-del-casale-marinara",
    description:
      "A slow-simmered tomato sauce made with Italian tomatoes, olive oil, basil, and a clean pantry ingredient list.",
    short_description: "Slow-simmered marinara with bright Italian tomato flavor",
    price: 8.5,
    original_price: null,
    category_id: "1",
    brand: "Le Bonta del Casale",
    sku: "PANTRY-004",
    stock: 72,
    images: [
      "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { weight: "340g", origin: "Campania, Italy" },
    rating: 4.6,
    review_count: 142,
    is_featured: true,
    is_new: true,
    tags: ["pantry", "sauce", "weeknight"],
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "p8",
    name: "Stovetop Espresso Morning Set",
    slug: "stovetop-espresso-morning-set",
    description:
      "A compact moka pot and ceramic cup pairing for a classic Italian morning ritual at home.",
    short_description: "Moka pot and cup set for daily espresso rituals",
    price: 64.0,
    original_price: 78.0,
    category_id: "2",
    brand: "Casa Milano",
    sku: "COFFEE-002",
    stock: 21,
    images: [
      "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { capacity: "3 cups", material: "Aluminum and ceramic" },
    rating: 4.9,
    review_count: 53,
    is_featured: false,
    is_new: true,
    tags: ["coffee", "morning", "giftable"],
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "p9",
    name: "Tuscan Host Gift Hamper",
    slug: "tuscan-host-gift-hamper",
    description:
      "A gift-ready assortment of pasta, sauce, olive oil, and sweet pantry accents for hosts and client gifting.",
    short_description: "Gift-ready Italian pantry bundle for hosts",
    price: 118.0,
    original_price: 136.0,
    category_id: "4",
    brand: "Mercato Curated",
    sku: "GIFT-001",
    stock: 16,
    images: [
      "https://images.pexels.com/photos/5874592/pexels-photo-5874592.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { items: "7", packaging: "Recyclable gift box" },
    rating: 4.9,
    review_count: 98,
    is_featured: true,
    is_new: true,
    tags: ["gift", "hosting", "curated"],
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: "p10",
    name: "Washed Linen Table Runner",
    slug: "washed-linen-table-runner",
    description:
      "A soft washed linen runner that brings a relaxed Mediterranean tone to everyday meals and dinner parties.",
    short_description: "Soft linen table layer for modern Mediterranean dining",
    price: 56.0,
    original_price: null,
    category_id: "3",
    brand: "Casa Fiorentina",
    sku: "DECOR-004",
    stock: 28,
    images: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    specifications: { length: "220cm", material: "100% washed linen" },
    rating: 4.7,
    review_count: 41,
    is_featured: false,
    is_new: true,
    tags: ["linen", "tabletop", "decor"],
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
];
